# 服务器配置
server.port=8080

# 数据库配置
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/movie_ticket?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA配置
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# 日志配置
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE

# 静态资源配置
spring.web.resources.static-locations=file:${user.dir}/uploads/,classpath:/static/
spring.mvc.static-path-pattern=/uploads/**

# 文件上传配置
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# 响应编码配置
spring.http.encoding.force=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
server.tomcat.uri-encoding=UTF-8

# 支付宝沙箱配置
alipay.appId=9021000163628387
alipay.appPrivateKey=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCNw1uNug0V7fGHVrFNmgsole8P+PgtAU08GpfRKFp1x2p9KE2hN/371F7NEcj2Jg8h1n0fW08hooKmoM/DfoU/a64emSrH54oDLgEH1IXMJZQpf/XCTuNXx9Cw6/hlqWM3jdaVjKF0gMSre7LdkCFlkv/TOt8k5aQNf/nUgPx4e628+y65mokfnXzZRDogS8sDB70uF+45P2KGk8FSQy9stE8xc5FvBW/ysVpuBgvqQ58LvCQxP/iGf4faDlf0OKr9FQSU8bnFkgJreHvbgGPzva31Wi5BbPYfBejYghrailThrwWuXWRb8Go9kDVTrr1HdvLg2+P67Jiiocxmuar3AgMBAAECggEAV7hf6aYLvNsczns1gWhlqTqF0GNl5itdCGkIMlN/DkxUN5f92VnVXsP92XU83huU14JqsEGHCLAPml390eFzQFg4SRTMJSDABNGtr5OxKy7BrKBSiWbZRJMPLrsFXJrhGxo4gxefPIEFsXr8ph8umzTH+oP+Wk2DIxtikz0xfLdSdC+b7W+1mkqpj8TbtwHV8UsYEhGpHjpXeEZdreLxmYcG/phDh1eM2045XvuKrpMqcLutCSnvrtZFN2b9cy731T74Nd2sVgSYc21M1RYMLn4s/JYfr72ocBF/jUqmW6GUQlq40T0AepOsMO8N8OIYDSw5etyfkc27T0BQ9ypOqQKBgQDqGcIVRnfwamTA1lCaTk/OK/Gzvud2ID6oHydBH5T4s77tOe4a82b/7l4XMV3iZ3u4chBzjBLyJrqhUpRsEt9cf7Ve+M2vAd4g9U1Tj1qnXgVmGvYei1VYt3Fu8LLYsW/PoLW5DpaAiKhy4SUPIlXu0iPv+JQV1z8mSdyaf/jyZQKBgQCbBk0HKVd3IWhO3JygJJ7pwyZ3cff4E4bc5JF//PFSP9Nyz8ZYIKIQ7eBuDG2euyxkmloJTvgumag6TrX+hudeO3nvwQICRPzb81BLJceHt/oMyVIP44+GIzuFB6S2fvt5qGH50gIn1cE3XKaL4oamYIqAnlHnIpPECjRXe/vkKwKBgQDfZhdVkDry/cUKVTr0FhmIaV0tp9dgXeMNMzWVqxrRv05LOkYkB/VZ9NJrlZu/a/ugB5H1gk2uMhFV0+V5wQTQU7r0V8CI6uJcV1ski5/6KfpC9yW5/kNC90RTl3VE3wcRf48Le4VaQY9mmb5w09ZnorfS0EgZE6Da3A+ejNM4FQKBgDHcgfP2uRopFZqf3ISpoq8/RGUQtBgHd84eein3WksBGmqIJ5x6yoW1bQUYXD28qBeniaQK0Upzw6cVX/YAv/QQHzUdGB9Qvx+jj8TL3vRpGTT5n7paj/Qt6tvrzG+iQhIsNW8bu/PCDcZXt32wm2xyCro5sdAsz+gy/AjTaP5HAoGAbduOE8FouuMU26OWTj2WsAyrkQuFE9x/Cn7sIZzg5HiKrKkYfaO28pr5yJ6InfiJqrwWXrgIwsaTF8z7d6Uuw+lcKxqudNvLu6Y9yW0j0rHLet7S7Fq5ci3eqJwYxVLm/Sr4/EpAyvsvWukKZPNSLX1tHpVgTsGhez6xHGpkiVc=
alipay.alipayPublicKey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwme2My8uiz5GcfVKSTs3kZ+ryXSFPbVbwwDOeL6kaKbRAzT50SVXA+7L9iENpeorOWSfGjhKmeqk/lj/tVptlCZJ8J+L3i2/+QtIaz5I30SdFk0SUJuKI7zliYQ9/KALahVfQKEZtrpegcgIosIAsYWVdT0BJwKbA341oo8mlxTOLr35K8cNbIgmvUX5e4IMPBKrVMzv2bqF9mN/pq15FIArVwXSDcVSIdFAncAaoor7AhoQRqQZZFoTDVnY1x9AVnMEG0RWvjcvHZ+joHnOHNeTkjKKTxEHMn8YVPGRfXzVFhmHLHcARvLXwU3ZWg3NNeftMpF+52Q9GNxV2VD8LQIDAQAB
alipay.gatewayUrl=https://openapi-sandbox.dl.alipaydev.com/gateway.do
alipay.signType=RSA2
alipay.charset=UTF-8
alipay.format=json
alipay.returnUrl=http://localhost:5173/payment/success
alipay.notifyUrl=http://localhost:8080/api/alipay/notify